### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by shedaniel** [EwyBoy/World-Stripper-Fabric#1]
Please keep cloth config references client side only.
Example: https://github.com/EwyBoy/World-Stripper-Fabric/blob/c67342e2434dc7bd751fc1da2272843d260161fb/src/main/java/com/ewyboy/worldstripper/config/Config.java#L74-L92

**Comment by EwyBoy** [comment]
ahh, I see. Thanks for the report. I will fix as soon as possible.

**Comment by EwyBoy** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/world-stripper-fabric/files/2862608
Thanks for reporting!
